name: Build Roll a Ball with NIS
on:
  push:
  workflow_dispatch:

jobs:
  build-macOS:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v3

      - run: |
          $UNITY_2021_3_HOME -batchmode -stackTraceLogType None -projectPath $CI_PROJECT_DIR -executeMethod Altom.AltTesterTools.BuildAltTester.MacBuildFromCommandLine -logFile buildMac.log -quit

      - run: ls
      - uses: actions/upload-artifact@v3.1.0
        if: always() # run this step even if one of the previous step failed
        with:
          name: BuildMacArtifact
          path: |
            RollABall.app
            buildMac.log